version: '3'
services:
  web:
    build: ./env
    links:
        - db
    ports:
        - "5000:5000"
    volumes:
        - .:/src
    networks:
        - apisfdev_default
  db:
    build: ./db
    ports:
        - "3306:3306"
    volumes:
        - ./dbdata:/var/lib/mysql
    networks:
        - apisfdev_default

networks:
  apisfdev_default:
    driver: bridge
